spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mango?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      #配置监控统计拦截的filters，去掉后监控界面SQL无法进行统计，wall用于防火墙
      filters: stat,wall,log4j,config
      #设置最大连接数
      max-active: 100
      #设置初始化大小
      initial-size: 1
      #设置获取连接等待超时时间
      max-wait: 60000
      #设置最小连接数
      min-idle: 1
      #设置间隔多久才能进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #设置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20

#MyBatis配置
mybatis:
  mapper-locations: classpath:sqlmap/*.xml
  type-aliases-package: com.ranyk.ssv.*.entity

#后台输出打印执行SQL
logging:
  level:
    com:
      ranyk: debug

#设置测试服务器启动端口和启动根目录配置
server:
  port: 8086
#设置项目启动根目录
#  servlet:
#    context-path: /ssv

#自定义属性值
custom:
  attributes:
    secret: abcdefg